### ISSUE TITLE
Enhanced_tilemap Plugin for Kibana 5.4.2

### ISSUE THREAD

**Issue by ankitgit** [nreese/enhanced_tilemap#85]
Hey Guys,

We want to use this plugin in one of the cluster which is running on Kibana 5.4.2 (upgrade not possible at present). Unfortunately, I din found any release for Kibana 5.4.2. It will be really nice if we can get the plugin for version 5.4.2 :smiley: .

Cheers, Ankit

**Comment by nreese** [comment]
5.4 is supported in with release https://github.com/nreese/enhanced_tilemap/releases/tag/v2017-09-23. Just change the version in package.json to 5.4.2

**Comment by ankitgit** [comment]
Hey Nathan,

Thanks for the reply :smiley: . I tried today what you asked but unfortunately it doesn't seem to help. I don't see the version incompatible error anymore, as I was seeing before, and kibana also says that the installation completed but seems like there is a problem.

Following are the execution logs: 

> root@testdwm-046 /usr/share/kibana/bin # ./kibana-plugin install http://<SERVER_ADDR>/pumosw/enhanced-tilemap-v2018-03-16-5.4.2.zip
Attempting to transfer from http://<SERVER_ADDR>/pumosw/enhanced-tilemap-v2018-03-16-5.4.2.zip
Transferring 6432602 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
root@testdwm-046 /usr/share/kibana/bin # ./kibana-plugin list
/usr/share/kibana/src/cli_plugin/list/list.js:26
        throw new Error('Unable to read package.json file for plugin ' + filename);
        ^
Error: Unable to read package.json file for plugin enhanced_tilemap
    at forEach.e (/usr/share/kibana/src/cli_plugin/list/list.js:26:15)
    at Array.forEach (native)
    at list (/usr/share/kibana/src/cli_plugin/list/list.js:13:44)
    at Command.processCommand (/usr/share/kibana/src/cli_plugin/list/index.js:38:22)
    at Command.<anonymous> (/usr/share/kibana/src/cli/command.js:93:20)
    at Command.listener (/usr/share/kibana/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/share/kibana/node_modules/commander/index.js:610:12)
    at Command.parse (/usr/share/kibana/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/share/kibana/src/cli_plugin/cli.js:54:9)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/share/kibana/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)


When I tried looking inside the plugins directory, I see an empty folder with the name of the plugin `/usr/share/kibana/plugins/enhanced_tilemap`.

Following is the content of the Json file post modification :

> {

  "name": "enhanced_tilemap",
  "version": "5.4.2",
  "scripts": {
    "test": "gulp test"
  },
  "devDependencies": {
    "babel-core": "6.22.1",
    "babel-preset-es2015": "6.22.0",
    "babel-register": "6.22.0",
    "chai": "3.5.0",
    "gulp": "3.9.1",
    "gulp-mocha": "3.0.1",
    "jsdom": "9.9.1",
    "jsdom-global": "2.1.1"
  }
}
 
Can you maybe think of a possible explanation for this behavior?
